name: music
path:
    log_dir: /mnt/ssd1/bin/logs/sttn
    checkpoint_dir: /mnt/ssd1/bin/checkpoints/sttn
    ave_ckpt_path: ave_I_350k.pth
    avnet_ckpt_path: avnet_music_pretrained.pth
dataset:
    name: MUSIC-Solo
    video_dir: datasets/MUSIC-Solo
    mask_dir: datasets/I-mask
    mask_type: I
    fps: 8
    audio_sr: 16000
    n_refs: 5
loss:
    lambda_l1: 1.0
    lambda_adv: 0.01
    adv_loss_type: hinge
    lambda_av_att: 0.0
    lambda_av_cls: 0.0
    num_clusters: 10
train:
    iter_total: 100000
    iter_log: 100
    iter_image_log: 200
    iter_checkpoint: 1000
    lr: 1.e-4
    iter_lr_update_1: 50000
    iter_lr_update_2: 100000
    batch_size: 8
    num_workers: 8
